### ISSUE TITLE
Play Store app says: you are offline

### ISSUE THREAD

**Issue by cmonty14** [sn-00-x/fakestore2playstore#5]
Hello,
I'm able to open Play Store app, but it says: you are offline.

Please advise.

THX

**Comment by sn-00-x** [comment]
I had the same problem on Android 12. Unfortunately I didn't have time to look at it, yet, cause I'm really busy with other tasks currently.

**Comment by Switch123456789** [comment]
Network access to the PlayStore-app seems to be disabled by default on Android 12. I just enabled it and now it is working fine.

I also recommend grant access to files and media. This enables the PlayStore to install big apps that access the Android/obb folder.

**Comment by cmonty14** [comment]
Could you please share details how you enabled network?
On my device it still shows: you are offline.

**Comment by Switch123456789** [comment]
1. Search "google play store" in android settings and tap it.
![Screenshot_20220818-151150_Lawnchair](https://user-images.githubusercontent.com/25269380/185404974-687c5eb1-0deb-41f9-9bdc-ece1c8628a29.png)
2. Tap "Mobile data and Wi-Fi"
![Screenshot_20220818-151126_Lawnchair_1](https://user-images.githubusercontent.com/25269380/185405450-a28602fe-3dc4-4a51-9d38-87e1dc4436b7.png)
3. Enable network access with highlighted switches.
![Screenshot_20220818-151202_Lawnchair](https://user-images.githubusercontent.com/25269380/185405658-b5881598-e26a-440f-835a-481f93afed1f.png)
You might need to clear the appdata BEFORE enabling network-access and/or restart the phone. Good luck!

**Comment by cmonty14** [comment]
Thanks for sharing these details.
